---
name: Compiler
on:
  push: null
jobs:

  alpine:
      name: Docker Build
      runs-on: ubuntu-latest
      steps:

        - name: Clone Repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 1

        - name: Setup Alpine Linux
          uses: jirutka/setup-alpine@v1
          with:
            branch: v3.20

        - name: Install Dependencies
          run: |
            apk add build-base libwebsockets-evlib_uv bsd-compat-headers cmake json-c-dev libuv-dev libwebsockets-dev openssl-dev>3 samurai zlib-dev
            
          shell: alpine.sh --root {0}

        - name: Compile ttyd
          run: |
            mkdir build && cd build
            cmake ..
            make && make install

          shell: alpine.sh --root {0}

        - name: Upload Binary
          uses: actions/upload-artifact@v4
          with:
            name: ttyd
            path: ../build/*
            retention-days: 5
